name: Android CI - Build Debug APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-

      - name: Install Android SDK packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip wget
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools" "$ANDROID_SDK_ROOT/platform-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline_tmp
          mv cmdline_tmp/cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          rm -rf cmdline.zip cmdline_tmp
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Accept licenses
        run: yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK (capture log)
        run: |
          set -o pipefail
          ./gradlew assembleDebug --no-daemon --stacktrace 2>&1 | tee build.log

      - name: Upload build artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            build.log
            app/build/outputs/apk/
            app/build/outputs/bundle/
            app/build/outputs/mapping/
